import {
  AmirIcon,
  AmeerahIcon,
  NaiAmeerIcon,
  NDAmeerIcon,
  NaiAmeerahIcon,
  FinSecIcon,
  GenSecIcon,
  EDChiefIcon,
  AMO,
  AssAmo,
  AssWel,
  ChairBus,
  CordIcon,
  DosIcon,
  ExOfficio,
  PROIcon,
  SecBus,
  SocWel,
} from '../ui/svg';

const CommitteeDetailss = [
  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Ameer',
    icon: <AmirIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'Ameerah',
    icon: <AmeerahIcon />,
  },
  {
    background: 'bg-[#F5E5D9]',
    name: 'Umar Zayad',
    post: 'Naibul Ameer(Admin)',
    icon: <NaiAmeerIcon />,
  },
  {
    background: 'bg-[#E6F4E6]',
    name: 'Umar Zayad',
    post: 'Naibul Ameer(Da’wah)',
    icon: <NDAmeerIcon />,
  },
  {
    background: 'bg-[#F1E2C8]',
    name: 'Umar Zayad',
    post: 'Naibul Ameerah',
    icon: <NaiAmeerahIcon />,
  },
  {
    background: 'bg-[#F6D9D9]',
    name: 'Umar Zayad',
    post: 'Financial Secretary',
    icon: <FinSecIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'General Secretary',
    icon: <GenSecIcon />,
  },
  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Editor-in-Chief',
    icon: <EDChiefIcon />,
  },
  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Director of Studies',
    icon: <DosIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'Assistant DOS 1',
    icon: <DosIcon />,
  },
  {
    background: 'bg-[#F5E5D9]',
    name: 'Umar Zayad',
    post: 'Assistant DOS 2',
    icon: <DosIcon />,
  },
  {
    background: 'bg-[#E6F4E6]',
    name: 'Umar Zayad',
    post: 'Assistant DOS 3',
    icon: <DosIcon />,
  },
  {
    background: 'bg-[#F1E2C8]',
    name: 'Umar Zayad',
    post: 'Divisional Coord 1',
    icon: <CordIcon />,
  },
  {
    background: 'bg-[#F6D9D9]',
    name: 'Umar Zayad',
    post: 'Divisional Coord 2',
    icon: <CordIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'Divisional Coord 3',
    icon: <CordIcon />,
  },
  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Divisional Coord 4',
    icon: <CordIcon />,
  },
  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Ass General Secretary 1',
    icon: <GenSecIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'PRO 1',
    icon: <PROIcon />,
  },
  {
    background: 'bg-[#F5E5D9]',
    name: 'Umar Zayad',
    post: 'PRO 2',
    icon: <PROIcon />,
  },
  {
    background: 'bg-[#E6F4E6]',
    name: 'Umar Zayad',
    post: 'PRO 3',
    icon: <PROIcon />,
  },
  {
    background: 'bg-[#F1E2C8]',
    name: 'Umar Zayad',
    post: 'Soc. and Welfare Officer',
    icon: <SocWel />,
  },
  {
    background: 'bg-[#F6D9D9]',
    name: 'Umar Zayad',
    post: 'Assistant DOS 3',
    icon: <DosIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'Ass. Welfare Officer',
    icon: <AssWel />,
  },
  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Treasurer',
    icon: <FinSecIcon />,
  },

  {
    background: 'bg-[#D9CDBE]',
    name: 'Umar Zayad',
    post: 'Ass General Secretary 2',
    icon: <GenSecIcon />,
  },
  {
    background: 'bg-[#CDCFAF]',
    name: 'Umar Zayad',
    post: 'Sec. Business Committee',
    icon: <SecBus />,
  },
  {
    background: 'bg-[#F5E5D9]',
    name: 'Umar Zayad',
    post: 'Chairman Business Cmt',
    icon: <ChairBus />,
  },
  {
    background: 'bg-[#E6F4E6]',
    name: 'Umar Zayad',
    post: 'AMO',
    icon: <AMO />,
  },
  {
    background: 'bg-[#F1E2C8]',
    name: 'Umar Zayad',
    post: 'Assistant AMO',
    icon: <AssAmo />,
  },
  {
    background: 'bg-[#F6D9D9]',
    name: 'Umar Zayad',
    post: 'Ex-Officio 1',
    icon: <ExOfficio />,
  },
];

export default CommitteeDetailss;
